{
# 公众号配置
# 公众号appId
"app_id": "wxe4f6d7251a56576b",
# 公众号appSecret
"app_secret": "10dd7ea42580ec39c7dc3b91eb6bc8d5",
# 模板消息id
"template_id": "GaLMWy49-5hJ2Xf6uh_O53SlJqccwyi8OrUbCADCmJ4",
# 接收公众号消息的微信号，如果有多个，需要在[]里用英文逗号间隔，例如["wx1", "wx2"]
"user": ["o-IMg5l3aGDu36t0G7jYASdYH4dU"],
 
# 信息配置
# 和风天气apikey
"weather_key": "3c49270830854be4beb1c86acedd1980",
# 所在地区，可为省，城市，区，县，同时支持国外城市，例如伦敦
"region": "泸州",
# 生日1，修改名字为对应需要显示的名字，如果生日为农历，在最前面加上r即可
"birthday1": {"name": "王薪翔", "birthday": "2003-04-08"},
# 生日2
"birthday2": {"name": "董星雨", "birthday": "2003-10-24"},
# 在一起的日子，格式同上，暂不不支持农历
"love_date": "2022-01-01",
# 金句中文，如果设置了，则会显示这里的，如果为空，默认会读取金山的每日金句
"note_ch": "",
# 金句英文
"note_en": ""
}
